directories:
  output: dist-widget
  buildResources: assets
files:
  - filter:
      - build/**/*
      - build/**/*
      - public/electron-widget.js
      - public/preload-widget.js
      - node_modules/**/*
extraMetadata:
  main: build/electron.js
appId: com.sarya.connective.widget
productName: HRMS Widget
mac:
  category: public.app-category.productivity
  target:
    - target: dmg
      arch:
        - x64
        - arm64
  icon: public/assets/icon.icns
win:
  target:
    - target: nsis
      arch:
        - x64
        - ia32
  icon: public/assets/icon.ico
  publisherName: Sarya Connective Team
  verifyUpdateCodeSignature: false
linux:
  target:
    - target: AppImage
      arch:
        - x64
  icon: public/assets/icon.png
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
publish: null
afterSign: null
forceCodeSigning: false
extends: react-cra
electronVersion: 27.3.11
